//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_Manager
    {
        public int EventID { get; set; }
        public string ТипСобытия { get; set; }
        public Nullable<System.DateTime> ДатаСобытия { get; set; }
        public string Подробности { get; set; }
    }
}
