//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dataBaseP8Entities : DbContext
    {
        public dataBaseP8Entities()
            : base("name=dataBaseP8Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BuyList> BuyList { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Custumers> Custumers { get; set; }
        public virtual DbSet<Event_Manager> Event_Manager { get; set; }
        public virtual DbSet<Postavki> Postavki { get; set; }
        public virtual DbSet<Postavshiki> Postavshiki { get; set; }
        public virtual DbSet<Posts> Posts { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SalePosition> SalePosition { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<Sklad> Sklad { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
    }
}
