//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postavki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Postavki()
        {
            this.BuyList = new HashSet<BuyList>();
        }
    
        public int PurchaseID { get; set; }
        public int ПоставщикID { get; set; }
        public Nullable<System.DateTime> ДатаПокупки { get; set; }
        public Nullable<decimal> ОбщаяСтоимость { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyList> BuyList { get; set; }
        public virtual Postavshiki Postavshiki { get; set; }
    }
}
